---
- name: Create cerbot's venv
  ansible.builtin.shell:
    cmd: python3 -m venv /opt/certbot/
    creates: /opt/certbot

- name: Update the venvs pip
  ansible.builtin.shell:
    cmd: /opt/certbot/bin/pip install --upgrade pip

- name: Install certbot
  ansible.builtin.shell:
    cmd: /opt/certbot/bin/pip install certbot certbot-nginx

- name: Certbot next steps
  ansible.builtin.debug:
    msg: "Please handle the interactive dialog provided by `certbot certonly --nginx` manually and re-run the playbook afterwards"
...
