---
# tasks file for library_application
- name: Ensure that the required applications are installed
  ansible.builtin.apt:
    pkg:
    - postgresql-all
    - nginx
    - python3
    - python3-venv
    - libaugeas0

- name: Clone the repository into the deployment directory
  ansible.builtin.git:
    repo: https://github.com/Sol-Mane/2401-waad-ica-1.git
    dest: "{{ deployment_dir }}/deployment"
    single_branch: yes
    version: master

- name: Include PostgreSQl related tasks
  ansible.builtin.include_tasks:
    file: "{% if deploy_database %}database_deployment{% else %}empty{% endif %}.yml"

- name: "{{ backend_deployment_templated_name }}"
  ansible.builtin.include_tasks:
    file: "{% if deploy_backend %}backend_deployment{% else %}empty{% endif %}.yml"
  vars:
    backend_deployment_templated_name: "{% if deploy_backend %}Deploying backend{% else %}Skipping backend deployment{% endif %}"

- name: Include Certbot's deployment tasks
  ansible.builtin.include_tasks:
    file: "{% if deploy_certbot %}certbot_deployment{% else %}empty{% endif %}.yml"

- name: Include frontend deployment tasks
  ansible.builtin.include_tasks:
    file: "{% if deploy_frontend %}frontend_deployment{% else %}empty{% endif %}.yml"

- name: Ensure that the unit files for the application exist
  ansible.builtin.template:
    src: "{{ unit_file }}"
    dest: /etc/systemd/system/
    owner: root
    group: root
    mode: '0644'
  register: unit_files_output
  loop_control:
    loop_var: unit_file
  loop:
    - backend.service
    - certbot-renewal.service
    - certbot-renewal.timer

- name: Reload systemd's daemons
  systemd:
    daemon_reload: True

- name: "{{ service_state_templated_name }}"
  ansible.builtin.systemd:
    name: service
    enabled: True
    state: "{% if unit_files_output.changed %}restarted{% else %}started{% endif %}"
  loop_control:
    loop_var: service
  loop:
    - backend.service
    - certbot-renewal.timer
  vars:
    service_state_templated_name: "Ensure that the unit files are enabled and {% if unit_files_output.changed %}re-started as they were changed{% else %}started{% endif %}"
...
